DATA:
  benchmark: 'crack500' # benchmark name, choices ['drive', 'cracktree200', 'crack500', 'roads]
  datapath: datasets/crack500
  classes: 1

MODEL:
  architecture: 'jtfn'
  backbone: 'resbase32'
  steps: 2
  use_gau: [True, True, True, True, True]
  use_fim: [True, True, True, True]
  up: [True, True, True, True]
  reduce_dim: False

TRAIN:
  logname: JTFN_crack500_train #save log and model
  train_gpu: [2]
  start_epoch: 0
  epochs: 2000
  img_mode: crop
  img_size: 360
  nworker: 8
  batch_size: 2  # batch size for training
  batch_size_val: 1
  evaluate: True
  resume: False # path to latest checkpoint (default: False), set the path for True
  optimizer: 'Adam'
  base_lr: 0.001
  lr_update: True
  lr_step: 10000
  ignore_label: 255
  weight_decay: 0.0005
  gamma: 0.95
  weight:
